# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teams/reco-arch/colossusdb/proto/common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='teams/reco-arch/colossusdb/proto/common.proto',
  package='colossusdb',
  syntax='proto3',
  serialized_pb=_b('\n-teams/reco-arch/colossusdb/proto/common.proto\x12\ncolossusdb\",\n\x0b\x45rrorStatus\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"Y\n\nReplicaHub\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02\x61z\x18\x02 \x01(\t\x12\x31\n\x10\x64isallowed_roles\x18\x03 \x03(\x0e\x32\x17.colossusdb.ReplicaRole\">\n\x13\x45rrorStatusResponse\x12\'\n\x06status\x18\x01 \x01(\x0b\x32\x17.colossusdb.ErrorStatus*H\n\x0bReplicaRole\x12\x0c\n\x08kPrimary\x10\x00\x12\x0e\n\nkSecondary\x10\x01\x12\x0c\n\x08kLearner\x10\x02\x12\r\n\x08kInvalid\x10\x91N*4\n\x0b\x41\x64minNodeOp\x12\t\n\x05kNoop\x10\x00\x12\x0c\n\x08kRestart\x10\x01\x12\x0c\n\x08kOffline\x10\x02\x42\x46\n\x1c\x63om.kuaishou.reco.colossusdbP\x01Z$github.com/kuaishou/colossusdb/pb;pbb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_REPLICAROLE = _descriptor.EnumDescriptor(
  name='ReplicaRole',
  full_name='colossusdb.ReplicaRole',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kPrimary', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kSecondary', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kLearner', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kInvalid', index=3, number=10001,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=262,
  serialized_end=334,
)
_sym_db.RegisterEnumDescriptor(_REPLICAROLE)

ReplicaRole = enum_type_wrapper.EnumTypeWrapper(_REPLICAROLE)
_ADMINNODEOP = _descriptor.EnumDescriptor(
  name='AdminNodeOp',
  full_name='colossusdb.AdminNodeOp',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='kNoop', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kRestart', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='kOffline', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=336,
  serialized_end=388,
)
_sym_db.RegisterEnumDescriptor(_ADMINNODEOP)

AdminNodeOp = enum_type_wrapper.EnumTypeWrapper(_ADMINNODEOP)
kPrimary = 0
kSecondary = 1
kLearner = 2
kInvalid = 10001
kNoop = 0
kRestart = 1
kOffline = 2



_ERRORSTATUS = _descriptor.Descriptor(
  name='ErrorStatus',
  full_name='colossusdb.ErrorStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='colossusdb.ErrorStatus.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='colossusdb.ErrorStatus.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=105,
)


_REPLICAHUB = _descriptor.Descriptor(
  name='ReplicaHub',
  full_name='colossusdb.ReplicaHub',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='colossusdb.ReplicaHub.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='az', full_name='colossusdb.ReplicaHub.az', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disallowed_roles', full_name='colossusdb.ReplicaHub.disallowed_roles', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=196,
)


_ERRORSTATUSRESPONSE = _descriptor.Descriptor(
  name='ErrorStatusResponse',
  full_name='colossusdb.ErrorStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='colossusdb.ErrorStatusResponse.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=260,
)

_REPLICAHUB.fields_by_name['disallowed_roles'].enum_type = _REPLICAROLE
_ERRORSTATUSRESPONSE.fields_by_name['status'].message_type = _ERRORSTATUS
DESCRIPTOR.message_types_by_name['ErrorStatus'] = _ERRORSTATUS
DESCRIPTOR.message_types_by_name['ReplicaHub'] = _REPLICAHUB
DESCRIPTOR.message_types_by_name['ErrorStatusResponse'] = _ERRORSTATUSRESPONSE
DESCRIPTOR.enum_types_by_name['ReplicaRole'] = _REPLICAROLE
DESCRIPTOR.enum_types_by_name['AdminNodeOp'] = _ADMINNODEOP

ErrorStatus = _reflection.GeneratedProtocolMessageType('ErrorStatus', (_message.Message,), dict(
  DESCRIPTOR = _ERRORSTATUS,
  __module__ = 'teams.reco_arch.colossusdb.proto.common_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.ErrorStatus)
  ))
_sym_db.RegisterMessage(ErrorStatus)

ReplicaHub = _reflection.GeneratedProtocolMessageType('ReplicaHub', (_message.Message,), dict(
  DESCRIPTOR = _REPLICAHUB,
  __module__ = 'teams.reco_arch.colossusdb.proto.common_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.ReplicaHub)
  ))
_sym_db.RegisterMessage(ReplicaHub)

ErrorStatusResponse = _reflection.GeneratedProtocolMessageType('ErrorStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _ERRORSTATUSRESPONSE,
  __module__ = 'teams.reco_arch.colossusdb.proto.common_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.ErrorStatusResponse)
  ))
_sym_db.RegisterMessage(ErrorStatusResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034com.kuaishou.reco.colossusdbP\001Z$github.com/kuaishou/colossusdb/pb;pb'))
# @@protoc_insertion_point(module_scope)
