# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teams/reco-arch/colossusdb/proto/kess_config_dir.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='teams/reco-arch/colossusdb/proto/kess_config_dir.proto',
  package='colossusdb',
  syntax='proto3',
  serialized_pb=_b('\n6teams/reco-arch/colossusdb/proto/kess_config_dir.proto\x12\ncolossusdb\"e\n\x0f\x43onfigItemValue\x12\x31\n\x06\x66ormat\x18\x01 \x01(\x0e\x32!.colossusdb.ConfigItemValueFormat\x12\x0e\n\x06schema\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\xda\x01\n\tConfigDir\x12\x0f\n\x07version\x18\x01 \x01(\x03\x12\x11\n\tsignature\x18\x02 \x01(\t\x12/\n\x05items\x18\x03 \x03(\x0b\x32 .colossusdb.ConfigDir.ItemsEntry\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\r\n\x05owner\x18\x05 \x01(\t\x12\x0b\n\x03mwi\x18\x06 \x01(\x03\x1aI\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.colossusdb.ConfigItemValue:\x02\x38\x01\"v\n\x0bModifyDirOp\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.colossusdb.ModifyDirOpType\x12\x11\n\titem_name\x18\x02 \x01(\t\x12)\n\x04item\x18\x03 \x01(\x0b\x32\x1b.colossusdb.ConfigItemValue\"\x8c\x01\n\x10ModifyDirRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x15\n\rhas_signature\x18\x02 \x01(\x08\x12\x11\n\tsignature\x18\x03 \x01(\t\x12$\n\x03ops\x18\x04 \x03(\x0b\x32\x17.colossusdb.ModifyDirOp\x12\r\n\x05owner\x18\x05 \x01(\t\x12\x0b\n\x03mwi\x18\x06 \x01(\x03*g\n\x15\x43onfigItemValueFormat\x12\n\n\x06STRING\x10\x00\x12\x08\n\x04LONG\x10\x01\x12\n\n\x06\x44OUBLE\x10\x02\x12\x08\n\x04\x42OOL\x10\x03\x12\n\n\x06\x42INARY\x10\x04\x12\x0c\n\x08PROTOBUF\x10\x05\x12\x08\n\x04ZSTD\x10\x06*&\n\x0fModifyDirOpType\x12\x07\n\x03PUT\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x42&Z$github.com/kuaishou/colossusdb/pb;pbb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_CONFIGITEMVALUEFORMAT = _descriptor.EnumDescriptor(
  name='ConfigItemValueFormat',
  full_name='colossusdb.ConfigItemValueFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LONG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOL', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BINARY', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROTOBUF', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ZSTD', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=657,
  serialized_end=760,
)
_sym_db.RegisterEnumDescriptor(_CONFIGITEMVALUEFORMAT)

ConfigItemValueFormat = enum_type_wrapper.EnumTypeWrapper(_CONFIGITEMVALUEFORMAT)
_MODIFYDIROPTYPE = _descriptor.EnumDescriptor(
  name='ModifyDirOpType',
  full_name='colossusdb.ModifyDirOpType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PUT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=762,
  serialized_end=800,
)
_sym_db.RegisterEnumDescriptor(_MODIFYDIROPTYPE)

ModifyDirOpType = enum_type_wrapper.EnumTypeWrapper(_MODIFYDIROPTYPE)
STRING = 0
LONG = 1
DOUBLE = 2
BOOL = 3
BINARY = 4
PROTOBUF = 5
ZSTD = 6
PUT = 0
DELETE = 1



_CONFIGITEMVALUE = _descriptor.Descriptor(
  name='ConfigItemValue',
  full_name='colossusdb.ConfigItemValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='format', full_name='colossusdb.ConfigItemValue.format', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='schema', full_name='colossusdb.ConfigItemValue.schema', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='colossusdb.ConfigItemValue.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=171,
)


_CONFIGDIR_ITEMSENTRY = _descriptor.Descriptor(
  name='ItemsEntry',
  full_name='colossusdb.ConfigDir.ItemsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='colossusdb.ConfigDir.ItemsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='colossusdb.ConfigDir.ItemsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=392,
)

_CONFIGDIR = _descriptor.Descriptor(
  name='ConfigDir',
  full_name='colossusdb.ConfigDir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='colossusdb.ConfigDir.version', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='colossusdb.ConfigDir.signature', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='colossusdb.ConfigDir.items', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='colossusdb.ConfigDir.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='colossusdb.ConfigDir.owner', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mwi', full_name='colossusdb.ConfigDir.mwi', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CONFIGDIR_ITEMSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=392,
)


_MODIFYDIROP = _descriptor.Descriptor(
  name='ModifyDirOp',
  full_name='colossusdb.ModifyDirOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='colossusdb.ModifyDirOp.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_name', full_name='colossusdb.ModifyDirOp.item_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item', full_name='colossusdb.ModifyDirOp.item', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=512,
)


_MODIFYDIRREQUEST = _descriptor.Descriptor(
  name='ModifyDirRequest',
  full_name='colossusdb.ModifyDirRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='colossusdb.ModifyDirRequest.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='has_signature', full_name='colossusdb.ModifyDirRequest.has_signature', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='colossusdb.ModifyDirRequest.signature', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ops', full_name='colossusdb.ModifyDirRequest.ops', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='colossusdb.ModifyDirRequest.owner', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mwi', full_name='colossusdb.ModifyDirRequest.mwi', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=655,
)

_CONFIGITEMVALUE.fields_by_name['format'].enum_type = _CONFIGITEMVALUEFORMAT
_CONFIGDIR_ITEMSENTRY.fields_by_name['value'].message_type = _CONFIGITEMVALUE
_CONFIGDIR_ITEMSENTRY.containing_type = _CONFIGDIR
_CONFIGDIR.fields_by_name['items'].message_type = _CONFIGDIR_ITEMSENTRY
_MODIFYDIROP.fields_by_name['type'].enum_type = _MODIFYDIROPTYPE
_MODIFYDIROP.fields_by_name['item'].message_type = _CONFIGITEMVALUE
_MODIFYDIRREQUEST.fields_by_name['ops'].message_type = _MODIFYDIROP
DESCRIPTOR.message_types_by_name['ConfigItemValue'] = _CONFIGITEMVALUE
DESCRIPTOR.message_types_by_name['ConfigDir'] = _CONFIGDIR
DESCRIPTOR.message_types_by_name['ModifyDirOp'] = _MODIFYDIROP
DESCRIPTOR.message_types_by_name['ModifyDirRequest'] = _MODIFYDIRREQUEST
DESCRIPTOR.enum_types_by_name['ConfigItemValueFormat'] = _CONFIGITEMVALUEFORMAT
DESCRIPTOR.enum_types_by_name['ModifyDirOpType'] = _MODIFYDIROPTYPE

ConfigItemValue = _reflection.GeneratedProtocolMessageType('ConfigItemValue', (_message.Message,), dict(
  DESCRIPTOR = _CONFIGITEMVALUE,
  __module__ = 'teams.reco_arch.colossusdb.proto.kess_config_dir_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.ConfigItemValue)
  ))
_sym_db.RegisterMessage(ConfigItemValue)

ConfigDir = _reflection.GeneratedProtocolMessageType('ConfigDir', (_message.Message,), dict(

  ItemsEntry = _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), dict(
    DESCRIPTOR = _CONFIGDIR_ITEMSENTRY,
    __module__ = 'teams.reco_arch.colossusdb.proto.kess_config_dir_pb2'
    # @@protoc_insertion_point(class_scope:colossusdb.ConfigDir.ItemsEntry)
    ))
  ,
  DESCRIPTOR = _CONFIGDIR,
  __module__ = 'teams.reco_arch.colossusdb.proto.kess_config_dir_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.ConfigDir)
  ))
_sym_db.RegisterMessage(ConfigDir)
_sym_db.RegisterMessage(ConfigDir.ItemsEntry)

ModifyDirOp = _reflection.GeneratedProtocolMessageType('ModifyDirOp', (_message.Message,), dict(
  DESCRIPTOR = _MODIFYDIROP,
  __module__ = 'teams.reco_arch.colossusdb.proto.kess_config_dir_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.ModifyDirOp)
  ))
_sym_db.RegisterMessage(ModifyDirOp)

ModifyDirRequest = _reflection.GeneratedProtocolMessageType('ModifyDirRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODIFYDIRREQUEST,
  __module__ = 'teams.reco_arch.colossusdb.proto.kess_config_dir_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.ModifyDirRequest)
  ))
_sym_db.RegisterMessage(ModifyDirRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z$github.com/kuaishou/colossusdb/pb;pb'))
_CONFIGDIR_ITEMSENTRY.has_options = True
_CONFIGDIR_ITEMSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
