# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teams/reco-arch/colossusdb/proto/mock_onebox_admin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from teams.reco_arch.colossusdb.proto import common_pb2 as teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='teams/reco-arch/colossusdb/proto/mock_onebox_admin.proto',
  package='colossusdb',
  syntax='proto3',
  serialized_pb=_b('\n8teams/reco-arch/colossusdb/proto/mock_onebox_admin.proto\x12\ncolossusdb\x1a-teams/reco-arch/colossusdb/proto/common.proto\"8\n\x0fStopNodeRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\"h\n\x10StartNodeRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x0b\n\x03paz\x18\x04 \x01(\t\x12\x12\n\nnode_index\x18\x05 \x01(\t2\xa7\x01\n\x0fMockOneboxAdmin\x12H\n\x08StopNode\x12\x1b.colossusdb.StopNodeRequest\x1a\x1f.colossusdb.ErrorStatusResponse\x12J\n\tStartNode\x12\x1c.colossusdb.StartNodeRequest\x1a\x1f.colossusdb.ErrorStatusResponseB&Z$github.com/kuaishou/colossusdb/pb;pbb\x06proto3')
  ,
  dependencies=[teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_STOPNODEREQUEST = _descriptor.Descriptor(
  name='StopNodeRequest',
  full_name='colossusdb.StopNodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='colossusdb.StopNodeRequest.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='colossusdb.StopNodeRequest.node_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=175,
)


_STARTNODEREQUEST = _descriptor.Descriptor(
  name='StartNodeRequest',
  full_name='colossusdb.StartNodeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='colossusdb.StartNodeRequest.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='colossusdb.StartNodeRequest.node_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='colossusdb.StartNodeRequest.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paz', full_name='colossusdb.StartNodeRequest.paz', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_index', full_name='colossusdb.StartNodeRequest.node_index', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=281,
)

DESCRIPTOR.message_types_by_name['StopNodeRequest'] = _STOPNODEREQUEST
DESCRIPTOR.message_types_by_name['StartNodeRequest'] = _STARTNODEREQUEST

StopNodeRequest = _reflection.GeneratedProtocolMessageType('StopNodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _STOPNODEREQUEST,
  __module__ = 'teams.reco_arch.colossusdb.proto.mock_onebox_admin_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.StopNodeRequest)
  ))
_sym_db.RegisterMessage(StopNodeRequest)

StartNodeRequest = _reflection.GeneratedProtocolMessageType('StartNodeRequest', (_message.Message,), dict(
  DESCRIPTOR = _STARTNODEREQUEST,
  __module__ = 'teams.reco_arch.colossusdb.proto.mock_onebox_admin_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.StartNodeRequest)
  ))
_sym_db.RegisterMessage(StartNodeRequest)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z$github.com/kuaishou/colossusdb/pb;pb'))
# @@protoc_insertion_point(module_scope)
