# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from teams.reco_arch.colossusdb.proto import common_pb2 as teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2
from teams.reco_arch.colossusdb.proto import partition_service_pb2 as teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2


class PartitionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddReplica = channel.unary_unary(
                '/colossusdb.PartitionService/AddReplica',
                request_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.AddReplicaRequest.SerializeToString,
                response_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
                )
        self.Reconfigure = channel.unary_unary(
                '/colossusdb.PartitionService/Reconfigure',
                request_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReconfigPartitionRequest.SerializeToString,
                response_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
                )
        self.RemoveReplica = channel.unary_unary(
                '/colossusdb.PartitionService/RemoveReplica',
                request_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.RemoveReplicaRequest.SerializeToString,
                response_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
                )
        self.GetReplicas = channel.unary_unary(
                '/colossusdb.PartitionService/GetReplicas',
                request_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.GetReplicasRequest.SerializeToString,
                response_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.GetReplicasResponse.FromString,
                )
        self.HandleCustomCommand = channel.unary_unary(
                '/colossusdb.PartitionService/HandleCustomCommand',
                request_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.CustomCommandRequest.SerializeToString,
                response_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.CustomCommandResponse.FromString,
                )
        self.ChangeAuthentication = channel.unary_unary(
                '/colossusdb.PartitionService/ChangeAuthentication',
                request_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ChangeAuthenticationRequest.SerializeToString,
                response_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
                )
        self.ReplicaSplit = channel.unary_unary(
                '/colossusdb.PartitionService/ReplicaSplit',
                request_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicaSplitRequest.SerializeToString,
                response_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
                )
        self.ReplicaSplitCleanup = channel.unary_unary(
                '/colossusdb.PartitionService/ReplicaSplitCleanup',
                request_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicaSplitCleanupRequest.SerializeToString,
                response_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
                )
        self.PrepareSwitchPrimary = channel.unary_unary(
                '/colossusdb.PartitionService/PrepareSwitchPrimary',
                request_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.PrepareSwitchPrimaryRequest.SerializeToString,
                response_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
                )
        self.GetReplicateInfo = channel.unary_unary(
                '/colossusdb.PartitionService/GetReplicateInfo',
                request_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicateInfoRequest.SerializeToString,
                response_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicateInfoResponse.FromString,
                )


class PartitionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reconfigure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveReplica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplicas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleCustomCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeAuthentication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicaSplit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicaSplitCleanup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareSwitchPrimary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplicateInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PartitionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReplica,
                    request_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.AddReplicaRequest.FromString,
                    response_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.SerializeToString,
            ),
            'Reconfigure': grpc.unary_unary_rpc_method_handler(
                    servicer.Reconfigure,
                    request_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReconfigPartitionRequest.FromString,
                    response_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.SerializeToString,
            ),
            'RemoveReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveReplica,
                    request_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.RemoveReplicaRequest.FromString,
                    response_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.SerializeToString,
            ),
            'GetReplicas': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicas,
                    request_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.GetReplicasRequest.FromString,
                    response_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.GetReplicasResponse.SerializeToString,
            ),
            'HandleCustomCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleCustomCommand,
                    request_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.CustomCommandRequest.FromString,
                    response_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.CustomCommandResponse.SerializeToString,
            ),
            'ChangeAuthentication': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeAuthentication,
                    request_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ChangeAuthenticationRequest.FromString,
                    response_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.SerializeToString,
            ),
            'ReplicaSplit': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicaSplit,
                    request_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicaSplitRequest.FromString,
                    response_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.SerializeToString,
            ),
            'ReplicaSplitCleanup': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicaSplitCleanup,
                    request_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicaSplitCleanupRequest.FromString,
                    response_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.SerializeToString,
            ),
            'PrepareSwitchPrimary': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareSwitchPrimary,
                    request_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.PrepareSwitchPrimaryRequest.FromString,
                    response_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.SerializeToString,
            ),
            'GetReplicateInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicateInfo,
                    request_deserializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicateInfoRequest.FromString,
                    response_serializer=teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicateInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'colossusdb.PartitionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PartitionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colossusdb.PartitionService/AddReplica',
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.AddReplicaRequest.SerializeToString,
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reconfigure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colossusdb.PartitionService/Reconfigure',
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReconfigPartitionRequest.SerializeToString,
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colossusdb.PartitionService/RemoveReplica',
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.RemoveReplicaRequest.SerializeToString,
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReplicas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colossusdb.PartitionService/GetReplicas',
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.GetReplicasRequest.SerializeToString,
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.GetReplicasResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HandleCustomCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colossusdb.PartitionService/HandleCustomCommand',
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.CustomCommandRequest.SerializeToString,
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.CustomCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeAuthentication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colossusdb.PartitionService/ChangeAuthentication',
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ChangeAuthenticationRequest.SerializeToString,
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicaSplit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colossusdb.PartitionService/ReplicaSplit',
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicaSplitRequest.SerializeToString,
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplicaSplitCleanup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colossusdb.PartitionService/ReplicaSplitCleanup',
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicaSplitCleanupRequest.SerializeToString,
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PrepareSwitchPrimary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colossusdb.PartitionService/PrepareSwitchPrimary',
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.PrepareSwitchPrimaryRequest.SerializeToString,
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.ErrorStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReplicateInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/colossusdb.PartitionService/GetReplicateInfo',
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicateInfoRequest.SerializeToString,
            teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_partition__service__pb2.ReplicateInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
