# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: teams/reco-arch/colossusdb/proto/route.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from teams.reco_arch.colossusdb.proto import common_pb2 as teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2
from teams.reco_arch.colossusdb.proto import replica_location_pb2 as teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_replica__location__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='teams/reco-arch/colossusdb/proto/route.proto',
  package='colossusdb',
  syntax='proto3',
  serialized_pb=_b('\n,teams/reco-arch/colossusdb/proto/route.proto\x12\ncolossusdb\x1a-teams/reco-arch/colossusdb/proto/common.proto\x1a\x37teams/reco-arch/colossusdb/proto/replica_location.proto\"j\n\x11PartitionLocation\x12-\n\x08replicas\x18\x01 \x03(\x0b\x32\x1b.colossusdb.ReplicaLocation\x12\x0f\n\x07version\x18\x02 \x01(\x03\x12\x15\n\rsplit_version\x18\x03 \x01(\x05\"\xdd\x01\n\x0eServerLocation\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x0e\n\x06hub_id\x18\x03 \x01(\x05\x12\x32\n\x04info\x18\x04 \x03(\x0b\x32$.colossusdb.ServerLocation.InfoEntry\x12\n\n\x02ip\x18\x05 \x01(\t\x12\r\n\x05\x61live\x18\x06 \x01(\x08\x12#\n\x02op\x18\x07 \x01(\x0e\x32\x17.colossusdb.AdminNodeOp\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"H\n\tTableInfo\x12\x13\n\x0bhash_method\x18\x01 \x01(\t\x12\x15\n\rsplit_version\x18\x02 \x01(\x05\x12\x0f\n\x07use_paz\x18\x03 \x01(\x08\"\'\n\x0c\x45ntriesBrief\x12\x17\n\x0fpartition_count\x18\x01 \x01(\x05\"\x9a\x01\n\tRouteMeta\x12\'\n\x06\x66ormat\x18\x01 \x01(\x0e\x32\x17.colossusdb.RouteFormat\x12\x10\n\x08route_id\x18\x02 \x01(\t\x12\x15\n\rsegment_count\x18\x03 \x01(\x05\x12\x12\n\nsegment_id\x18\x04 \x01(\x05\x12\'\n\x05\x62rief\x18\x05 \x01(\x0b\x32\x18.colossusdb.EntriesBrief\"\xc7\x01\n\x0cRouteEntries\x12)\n\ntable_info\x18\x01 \x01(\x0b\x32\x15.colossusdb.TableInfo\x12\x31\n\npartitions\x18\x02 \x03(\x0b\x32\x1d.colossusdb.PartitionLocation\x12+\n\x07servers\x18\x03 \x03(\x0b\x32\x1a.colossusdb.ServerLocation\x12,\n\x0creplica_hubs\x18\x04 \x03(\x0b\x32\x16.colossusdb.ReplicaHub*\'\n\x0bRouteFormat\x12\x08\n\x04JSON\x10\x00\x12\x0e\n\nGZIPPED_PB\x10\x01\x42\x46\n\x1c\x63om.kuaishou.reco.colossusdbP\x01Z$github.com/kuaishou/colossusdb/pb;pbb\x06proto3')
  ,
  dependencies=[teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2.DESCRIPTOR,teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_replica__location__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ROUTEFORMAT = _descriptor.EnumDescriptor(
  name='RouteFormat',
  full_name='colossusdb.RouteFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='JSON', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GZIPPED_PB', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=970,
  serialized_end=1009,
)
_sym_db.RegisterEnumDescriptor(_ROUTEFORMAT)

RouteFormat = enum_type_wrapper.EnumTypeWrapper(_ROUTEFORMAT)
JSON = 0
GZIPPED_PB = 1



_PARTITIONLOCATION = _descriptor.Descriptor(
  name='PartitionLocation',
  full_name='colossusdb.PartitionLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='replicas', full_name='colossusdb.PartitionLocation.replicas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='colossusdb.PartitionLocation.version', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='split_version', full_name='colossusdb.PartitionLocation.split_version', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=270,
)


_SERVERLOCATION_INFOENTRY = _descriptor.Descriptor(
  name='InfoEntry',
  full_name='colossusdb.ServerLocation.InfoEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='colossusdb.ServerLocation.InfoEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='colossusdb.ServerLocation.InfoEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=451,
  serialized_end=494,
)

_SERVERLOCATION = _descriptor.Descriptor(
  name='ServerLocation',
  full_name='colossusdb.ServerLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='colossusdb.ServerLocation.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='colossusdb.ServerLocation.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hub_id', full_name='colossusdb.ServerLocation.hub_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='info', full_name='colossusdb.ServerLocation.info', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='colossusdb.ServerLocation.ip', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alive', full_name='colossusdb.ServerLocation.alive', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='op', full_name='colossusdb.ServerLocation.op', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SERVERLOCATION_INFOENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=494,
)


_TABLEINFO = _descriptor.Descriptor(
  name='TableInfo',
  full_name='colossusdb.TableInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash_method', full_name='colossusdb.TableInfo.hash_method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='split_version', full_name='colossusdb.TableInfo.split_version', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_paz', full_name='colossusdb.TableInfo.use_paz', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=496,
  serialized_end=568,
)


_ENTRIESBRIEF = _descriptor.Descriptor(
  name='EntriesBrief',
  full_name='colossusdb.EntriesBrief',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partition_count', full_name='colossusdb.EntriesBrief.partition_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=570,
  serialized_end=609,
)


_ROUTEMETA = _descriptor.Descriptor(
  name='RouteMeta',
  full_name='colossusdb.RouteMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='format', full_name='colossusdb.RouteMeta.format', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='route_id', full_name='colossusdb.RouteMeta.route_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segment_count', full_name='colossusdb.RouteMeta.segment_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='segment_id', full_name='colossusdb.RouteMeta.segment_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='brief', full_name='colossusdb.RouteMeta.brief', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=612,
  serialized_end=766,
)


_ROUTEENTRIES = _descriptor.Descriptor(
  name='RouteEntries',
  full_name='colossusdb.RouteEntries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_info', full_name='colossusdb.RouteEntries.table_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='partitions', full_name='colossusdb.RouteEntries.partitions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='servers', full_name='colossusdb.RouteEntries.servers', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='replica_hubs', full_name='colossusdb.RouteEntries.replica_hubs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=769,
  serialized_end=968,
)

_PARTITIONLOCATION.fields_by_name['replicas'].message_type = teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_replica__location__pb2._REPLICALOCATION
_SERVERLOCATION_INFOENTRY.containing_type = _SERVERLOCATION
_SERVERLOCATION.fields_by_name['info'].message_type = _SERVERLOCATION_INFOENTRY
_SERVERLOCATION.fields_by_name['op'].enum_type = teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2._ADMINNODEOP
_ROUTEMETA.fields_by_name['format'].enum_type = _ROUTEFORMAT
_ROUTEMETA.fields_by_name['brief'].message_type = _ENTRIESBRIEF
_ROUTEENTRIES.fields_by_name['table_info'].message_type = _TABLEINFO
_ROUTEENTRIES.fields_by_name['partitions'].message_type = _PARTITIONLOCATION
_ROUTEENTRIES.fields_by_name['servers'].message_type = _SERVERLOCATION
_ROUTEENTRIES.fields_by_name['replica_hubs'].message_type = teams_dot_reco__arch_dot_colossusdb_dot_proto_dot_common__pb2._REPLICAHUB
DESCRIPTOR.message_types_by_name['PartitionLocation'] = _PARTITIONLOCATION
DESCRIPTOR.message_types_by_name['ServerLocation'] = _SERVERLOCATION
DESCRIPTOR.message_types_by_name['TableInfo'] = _TABLEINFO
DESCRIPTOR.message_types_by_name['EntriesBrief'] = _ENTRIESBRIEF
DESCRIPTOR.message_types_by_name['RouteMeta'] = _ROUTEMETA
DESCRIPTOR.message_types_by_name['RouteEntries'] = _ROUTEENTRIES
DESCRIPTOR.enum_types_by_name['RouteFormat'] = _ROUTEFORMAT

PartitionLocation = _reflection.GeneratedProtocolMessageType('PartitionLocation', (_message.Message,), dict(
  DESCRIPTOR = _PARTITIONLOCATION,
  __module__ = 'teams.reco_arch.colossusdb.proto.route_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.PartitionLocation)
  ))
_sym_db.RegisterMessage(PartitionLocation)

ServerLocation = _reflection.GeneratedProtocolMessageType('ServerLocation', (_message.Message,), dict(

  InfoEntry = _reflection.GeneratedProtocolMessageType('InfoEntry', (_message.Message,), dict(
    DESCRIPTOR = _SERVERLOCATION_INFOENTRY,
    __module__ = 'teams.reco_arch.colossusdb.proto.route_pb2'
    # @@protoc_insertion_point(class_scope:colossusdb.ServerLocation.InfoEntry)
    ))
  ,
  DESCRIPTOR = _SERVERLOCATION,
  __module__ = 'teams.reco_arch.colossusdb.proto.route_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.ServerLocation)
  ))
_sym_db.RegisterMessage(ServerLocation)
_sym_db.RegisterMessage(ServerLocation.InfoEntry)

TableInfo = _reflection.GeneratedProtocolMessageType('TableInfo', (_message.Message,), dict(
  DESCRIPTOR = _TABLEINFO,
  __module__ = 'teams.reco_arch.colossusdb.proto.route_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.TableInfo)
  ))
_sym_db.RegisterMessage(TableInfo)

EntriesBrief = _reflection.GeneratedProtocolMessageType('EntriesBrief', (_message.Message,), dict(
  DESCRIPTOR = _ENTRIESBRIEF,
  __module__ = 'teams.reco_arch.colossusdb.proto.route_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.EntriesBrief)
  ))
_sym_db.RegisterMessage(EntriesBrief)

RouteMeta = _reflection.GeneratedProtocolMessageType('RouteMeta', (_message.Message,), dict(
  DESCRIPTOR = _ROUTEMETA,
  __module__ = 'teams.reco_arch.colossusdb.proto.route_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.RouteMeta)
  ))
_sym_db.RegisterMessage(RouteMeta)

RouteEntries = _reflection.GeneratedProtocolMessageType('RouteEntries', (_message.Message,), dict(
  DESCRIPTOR = _ROUTEENTRIES,
  __module__ = 'teams.reco_arch.colossusdb.proto.route_pb2'
  # @@protoc_insertion_point(class_scope:colossusdb.RouteEntries)
  ))
_sym_db.RegisterMessage(RouteEntries)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034com.kuaishou.reco.colossusdbP\001Z$github.com/kuaishou/colossusdb/pb;pb'))
_SERVERLOCATION_INFOENTRY.has_options = True
_SERVERLOCATION_INFOENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
