// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        (unknown)
// source: teams/reco-arch/colossusdb/proto/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicaRole int32

const (
	ReplicaRole_kPrimary   ReplicaRole = 0
	ReplicaRole_kSecondary ReplicaRole = 1
	ReplicaRole_kLearner   ReplicaRole = 2
	ReplicaRole_kInvalid   ReplicaRole = 10001
)

// Enum value maps for ReplicaRole.
var (
	ReplicaRole_name = map[int32]string{
		0:     "kPrimary",
		1:     "kSecondary",
		2:     "kLearner",
		10001: "kInvalid",
	}
	ReplicaRole_value = map[string]int32{
		"kPrimary":   0,
		"kSecondary": 1,
		"kLearner":   2,
		"kInvalid":   10001,
	}
)

func (x ReplicaRole) Enum() *ReplicaRole {
	p := new(ReplicaRole)
	*p = x
	return p
}

func (x ReplicaRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplicaRole) Descriptor() protoreflect.EnumDescriptor {
	return file_teams_reco_arch_colossusdb_proto_common_proto_enumTypes[0].Descriptor()
}

func (ReplicaRole) Type() protoreflect.EnumType {
	return &file_teams_reco_arch_colossusdb_proto_common_proto_enumTypes[0]
}

func (x ReplicaRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplicaRole.Descriptor instead.
func (ReplicaRole) EnumDescriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_common_proto_rawDescGZIP(), []int{0}
}

type AdminNodeOp int32

const (
	AdminNodeOp_kNoop    AdminNodeOp = 0
	AdminNodeOp_kRestart AdminNodeOp = 1
	AdminNodeOp_kOffline AdminNodeOp = 2
)

// Enum value maps for AdminNodeOp.
var (
	AdminNodeOp_name = map[int32]string{
		0: "kNoop",
		1: "kRestart",
		2: "kOffline",
	}
	AdminNodeOp_value = map[string]int32{
		"kNoop":    0,
		"kRestart": 1,
		"kOffline": 2,
	}
)

func (x AdminNodeOp) Enum() *AdminNodeOp {
	p := new(AdminNodeOp)
	*p = x
	return p
}

func (x AdminNodeOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminNodeOp) Descriptor() protoreflect.EnumDescriptor {
	return file_teams_reco_arch_colossusdb_proto_common_proto_enumTypes[1].Descriptor()
}

func (AdminNodeOp) Type() protoreflect.EnumType {
	return &file_teams_reco_arch_colossusdb_proto_common_proto_enumTypes[1]
}

func (x AdminNodeOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminNodeOp.Descriptor instead.
func (AdminNodeOp) EnumDescriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_common_proto_rawDescGZIP(), []int{1}
}

type ErrorStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
}

func (x *ErrorStatus) Reset() {
	*x = ErrorStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStatus) ProtoMessage() {}

func (x *ErrorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStatus.ProtoReflect.Descriptor instead.
func (*ErrorStatus) Descriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReplicaHub struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Az   string `protobuf:"bytes,2,opt,name=az,proto3" json:"az"`
	// roles in `disallowed_roles` are disallowed to exist in this hub
	DisallowedRoles []ReplicaRole `protobuf:"varint,3,rep,packed,name=disallowed_roles,json=disallowedRoles,proto3,enum=colossusdb.ReplicaRole" json:"disallowed_roles"`
}

func (x *ReplicaHub) Reset() {
	*x = ReplicaHub{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicaHub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaHub) ProtoMessage() {}

func (x *ReplicaHub) ProtoReflect() protoreflect.Message {
	mi := &file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaHub.ProtoReflect.Descriptor instead.
func (*ReplicaHub) Descriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicaHub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReplicaHub) GetAz() string {
	if x != nil {
		return x.Az
	}
	return ""
}

func (x *ReplicaHub) GetDisallowedRoles() []ReplicaRole {
	if x != nil {
		return x.DisallowedRoles
	}
	return nil
}

// wrap ErrorStatus into another message
// so as to make every http-json response
// will have the common format:
//
//	{
//	   "status": {
//	       "code": code,
//	       "message": "xxxxx"
//	   }
//	}
type ErrorStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *ErrorStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status"`
}

func (x *ErrorStatusResponse) Reset() {
	*x = ErrorStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorStatusResponse) ProtoMessage() {}

func (x *ErrorStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorStatusResponse.ProtoReflect.Descriptor instead.
func (*ErrorStatusResponse) Descriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorStatusResponse) GetStatus() *ErrorStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_teams_reco_arch_colossusdb_proto_common_proto protoreflect.FileDescriptor

var file_teams_reco_arch_colossusdb_proto_common_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x2d, 0x61, 0x72, 0x63,
	0x68, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x22, 0x3b, 0x0a, 0x0b, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x74, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x48, 0x75, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x61, 0x7a,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x61, 0x7a, 0x12, 0x42, 0x0a, 0x10, 0x64, 0x69,
	0x73, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64,
	0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x0f, 0x64,
	0x69, 0x73, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0x46,
	0x0a, 0x13, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73,
	0x64, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x48, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x6b, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x79, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x6b, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72,
	0x79, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x6b, 0x4c, 0x65, 0x61, 0x72, 0x6e, 0x65, 0x72, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x08, 0x6b, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10, 0x91, 0x4e,
	0x2a, 0x34, 0x0a, 0x0b, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x4f, 0x70, 0x12,
	0x09, 0x0a, 0x05, 0x6b, 0x4e, 0x6f, 0x6f, 0x70, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x6b, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x72, 0x74, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x6b, 0x4f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x10, 0x02, 0x42, 0x46, 0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x75,
	0x61, 0x69, 0x73, 0x68, 0x6f, 0x75, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x6f,
	0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x50, 0x01, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x61, 0x69, 0x73, 0x68, 0x6f, 0x75, 0x2f, 0x63, 0x6f,
	0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teams_reco_arch_colossusdb_proto_common_proto_rawDescOnce sync.Once
	file_teams_reco_arch_colossusdb_proto_common_proto_rawDescData = file_teams_reco_arch_colossusdb_proto_common_proto_rawDesc
)

func file_teams_reco_arch_colossusdb_proto_common_proto_rawDescGZIP() []byte {
	file_teams_reco_arch_colossusdb_proto_common_proto_rawDescOnce.Do(func() {
		file_teams_reco_arch_colossusdb_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_teams_reco_arch_colossusdb_proto_common_proto_rawDescData)
	})
	return file_teams_reco_arch_colossusdb_proto_common_proto_rawDescData
}

var file_teams_reco_arch_colossusdb_proto_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_teams_reco_arch_colossusdb_proto_common_proto_goTypes = []interface{}{
	(ReplicaRole)(0),            // 0: colossusdb.ReplicaRole
	(AdminNodeOp)(0),            // 1: colossusdb.AdminNodeOp
	(*ErrorStatus)(nil),         // 2: colossusdb.ErrorStatus
	(*ReplicaHub)(nil),          // 3: colossusdb.ReplicaHub
	(*ErrorStatusResponse)(nil), // 4: colossusdb.ErrorStatusResponse
}
var file_teams_reco_arch_colossusdb_proto_common_proto_depIdxs = []int32{
	0, // 0: colossusdb.ReplicaHub.disallowed_roles:type_name -> colossusdb.ReplicaRole
	2, // 1: colossusdb.ErrorStatusResponse.status:type_name -> colossusdb.ErrorStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_teams_reco_arch_colossusdb_proto_common_proto_init() }
func file_teams_reco_arch_colossusdb_proto_common_proto_init() {
	if File_teams_reco_arch_colossusdb_proto_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicaHub); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teams_reco_arch_colossusdb_proto_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teams_reco_arch_colossusdb_proto_common_proto_goTypes,
		DependencyIndexes: file_teams_reco_arch_colossusdb_proto_common_proto_depIdxs,
		EnumInfos:         file_teams_reco_arch_colossusdb_proto_common_proto_enumTypes,
		MessageInfos:      file_teams_reco_arch_colossusdb_proto_common_proto_msgTypes,
	}.Build()
	File_teams_reco_arch_colossusdb_proto_common_proto = out.File
	file_teams_reco_arch_colossusdb_proto_common_proto_rawDesc = nil
	file_teams_reco_arch_colossusdb_proto_common_proto_goTypes = nil
	file_teams_reco_arch_colossusdb_proto_common_proto_depIdxs = nil
}
