// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        (unknown)
// source: teams/reco-arch/colossusdb/proto/kess_config_dir.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigItemValueFormat int32

const (
	ConfigItemValueFormat_STRING   ConfigItemValueFormat = 0
	ConfigItemValueFormat_LONG     ConfigItemValueFormat = 1
	ConfigItemValueFormat_DOUBLE   ConfigItemValueFormat = 2
	ConfigItemValueFormat_BOOL     ConfigItemValueFormat = 3
	ConfigItemValueFormat_BINARY   ConfigItemValueFormat = 4
	ConfigItemValueFormat_PROTOBUF ConfigItemValueFormat = 5
	ConfigItemValueFormat_ZSTD     ConfigItemValueFormat = 6
)

// Enum value maps for ConfigItemValueFormat.
var (
	ConfigItemValueFormat_name = map[int32]string{
		0: "STRING",
		1: "LONG",
		2: "DOUBLE",
		3: "BOOL",
		4: "BINARY",
		5: "PROTOBUF",
		6: "ZSTD",
	}
	ConfigItemValueFormat_value = map[string]int32{
		"STRING":   0,
		"LONG":     1,
		"DOUBLE":   2,
		"BOOL":     3,
		"BINARY":   4,
		"PROTOBUF": 5,
		"ZSTD":     6,
	}
)

func (x ConfigItemValueFormat) Enum() *ConfigItemValueFormat {
	p := new(ConfigItemValueFormat)
	*p = x
	return p
}

func (x ConfigItemValueFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConfigItemValueFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_enumTypes[0].Descriptor()
}

func (ConfigItemValueFormat) Type() protoreflect.EnumType {
	return &file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_enumTypes[0]
}

func (x ConfigItemValueFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConfigItemValueFormat.Descriptor instead.
func (ConfigItemValueFormat) EnumDescriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescGZIP(), []int{0}
}

type ModifyDirOpType int32

const (
	ModifyDirOpType_PUT    ModifyDirOpType = 0
	ModifyDirOpType_DELETE ModifyDirOpType = 1
)

// Enum value maps for ModifyDirOpType.
var (
	ModifyDirOpType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
	}
	ModifyDirOpType_value = map[string]int32{
		"PUT":    0,
		"DELETE": 1,
	}
)

func (x ModifyDirOpType) Enum() *ModifyDirOpType {
	p := new(ModifyDirOpType)
	*p = x
	return p
}

func (x ModifyDirOpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModifyDirOpType) Descriptor() protoreflect.EnumDescriptor {
	return file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_enumTypes[1].Descriptor()
}

func (ModifyDirOpType) Type() protoreflect.EnumType {
	return &file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_enumTypes[1]
}

func (x ModifyDirOpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModifyDirOpType.Descriptor instead.
func (ModifyDirOpType) EnumDescriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescGZIP(), []int{1}
}

type ConfigItemValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format  ConfigItemValueFormat `protobuf:"varint,1,opt,name=format,proto3,enum=colossusdb.ConfigItemValueFormat" json:"format"`
	Schema  string                `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema"`
	Content string                `protobuf:"bytes,3,opt,name=content,proto3" json:"content"`
}

func (x *ConfigItemValue) Reset() {
	*x = ConfigItemValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigItemValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigItemValue) ProtoMessage() {}

func (x *ConfigItemValue) ProtoReflect() protoreflect.Message {
	mi := &file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigItemValue.ProtoReflect.Descriptor instead.
func (*ConfigItemValue) Descriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigItemValue) GetFormat() ConfigItemValueFormat {
	if x != nil {
		return x.Format
	}
	return ConfigItemValueFormat_STRING
}

func (x *ConfigItemValue) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *ConfigItemValue) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ConfigDir struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   int64                       `protobuf:"varint,1,opt,name=version,proto3" json:"version"`
	Signature string                      `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature"`
	Items     map[string]*ConfigItemValue `protobuf:"bytes,3,rep,name=items,proto3" json:"items" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp int64                       `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp"`
	Owner     string                      `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner"`
	Mwi       int64                       `protobuf:"varint,6,opt,name=mwi,proto3" json:"mwi"`
}

func (x *ConfigDir) Reset() {
	*x = ConfigDir{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigDir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDir) ProtoMessage() {}

func (x *ConfigDir) ProtoReflect() protoreflect.Message {
	mi := &file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDir.ProtoReflect.Descriptor instead.
func (*ConfigDir) Descriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigDir) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConfigDir) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ConfigDir) GetItems() map[string]*ConfigItemValue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ConfigDir) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConfigDir) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ConfigDir) GetMwi() int64 {
	if x != nil {
		return x.Mwi
	}
	return 0
}

type ModifyDirOp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     ModifyDirOpType  `protobuf:"varint,1,opt,name=type,proto3,enum=colossusdb.ModifyDirOpType" json:"type"`
	ItemName string           `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name"`
	Item     *ConfigItemValue `protobuf:"bytes,3,opt,name=item,proto3" json:"item"`
}

func (x *ModifyDirOp) Reset() {
	*x = ModifyDirOp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyDirOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyDirOp) ProtoMessage() {}

func (x *ModifyDirOp) ProtoReflect() protoreflect.Message {
	mi := &file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyDirOp.ProtoReflect.Descriptor instead.
func (*ModifyDirOp) Descriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescGZIP(), []int{2}
}

func (x *ModifyDirOp) GetType() ModifyDirOpType {
	if x != nil {
		return x.Type
	}
	return ModifyDirOpType_PUT
}

func (x *ModifyDirOp) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *ModifyDirOp) GetItem() *ConfigItemValue {
	if x != nil {
		return x.Item
	}
	return nil
}

type ModifyDirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path         string         `protobuf:"bytes,1,opt,name=path,proto3" json:"path"`
	HasSignature bool           `protobuf:"varint,2,opt,name=has_signature,json=hasSignature,proto3" json:"has_signature"`
	Signature    string         `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature"`
	Ops          []*ModifyDirOp `protobuf:"bytes,4,rep,name=ops,proto3" json:"ops"`
	Owner        string         `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner"`
	Mwi          int64          `protobuf:"varint,6,opt,name=mwi,proto3" json:"mwi"`
}

func (x *ModifyDirRequest) Reset() {
	*x = ModifyDirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyDirRequest) ProtoMessage() {}

func (x *ModifyDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyDirRequest.ProtoReflect.Descriptor instead.
func (*ModifyDirRequest) Descriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescGZIP(), []int{3}
}

func (x *ModifyDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ModifyDirRequest) GetHasSignature() bool {
	if x != nil {
		return x.HasSignature
	}
	return false
}

func (x *ModifyDirRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ModifyDirRequest) GetOps() []*ModifyDirOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *ModifyDirRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ModifyDirRequest) GetMwi() int64 {
	if x != nil {
		return x.Mwi
	}
	return 0
}

var File_teams_reco_arch_colossusdb_proto_kess_config_dir_proto protoreflect.FileDescriptor

var file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDesc = []byte{
	0x0a, 0x36, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x2d, 0x61, 0x72, 0x63,
	0x68, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6b, 0x65, 0x73, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x64,
	0x69, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73,
	0x75, 0x73, 0x64, 0x62, 0x22, 0x7e, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74,
	0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x39, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73,
	0x75, 0x73, 0x64, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x22, 0x98, 0x02, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44,
	0x69, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x36, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63, 0x6f, 0x6c, 0x6f,
	0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x69, 0x72,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x77, 0x69, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x77, 0x69, 0x1a, 0x55, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x31, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73,
	0x75, 0x73, 0x64, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22,
	0x8c, 0x01, 0x0a, 0x0b, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x44, 0x69, 0x72, 0x4f, 0x70, 0x12,
	0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66,
	0x79, 0x44, 0x69, 0x72, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a,
	0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6f,
	0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49,
	0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0xbc,
	0x01, 0x0a, 0x10, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x68, 0x61, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x29, 0x0a, 0x03, 0x6f, 0x70,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73,
	0x75, 0x73, 0x64, 0x62, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x44, 0x69, 0x72, 0x4f, 0x70,
	0x52, 0x03, 0x6f, 0x70, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x77, 0x69, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6d, 0x77, 0x69, 0x2a, 0x67, 0x0a,
	0x15, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c,
	0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x04, 0x12, 0x0c,
	0x0a, 0x08, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x42, 0x55, 0x46, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04,
	0x5a, 0x53, 0x54, 0x44, 0x10, 0x06, 0x2a, 0x26, 0x0a, 0x0f, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x44, 0x69, 0x72, 0x4f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x50, 0x55, 0x54,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01, 0x42, 0x26,
	0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x61,
	0x69, 0x73, 0x68, 0x6f, 0x75, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62,
	0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescOnce sync.Once
	file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescData = file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDesc
)

func file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescGZIP() []byte {
	file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescOnce.Do(func() {
		file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescData = protoimpl.X.CompressGZIP(file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescData)
	})
	return file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDescData
}

var file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_goTypes = []interface{}{
	(ConfigItemValueFormat)(0), // 0: colossusdb.ConfigItemValueFormat
	(ModifyDirOpType)(0),       // 1: colossusdb.ModifyDirOpType
	(*ConfigItemValue)(nil),    // 2: colossusdb.ConfigItemValue
	(*ConfigDir)(nil),          // 3: colossusdb.ConfigDir
	(*ModifyDirOp)(nil),        // 4: colossusdb.ModifyDirOp
	(*ModifyDirRequest)(nil),   // 5: colossusdb.ModifyDirRequest
	nil,                        // 6: colossusdb.ConfigDir.ItemsEntry
}
var file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_depIdxs = []int32{
	0, // 0: colossusdb.ConfigItemValue.format:type_name -> colossusdb.ConfigItemValueFormat
	6, // 1: colossusdb.ConfigDir.items:type_name -> colossusdb.ConfigDir.ItemsEntry
	1, // 2: colossusdb.ModifyDirOp.type:type_name -> colossusdb.ModifyDirOpType
	2, // 3: colossusdb.ModifyDirOp.item:type_name -> colossusdb.ConfigItemValue
	4, // 4: colossusdb.ModifyDirRequest.ops:type_name -> colossusdb.ModifyDirOp
	2, // 5: colossusdb.ConfigDir.ItemsEntry.value:type_name -> colossusdb.ConfigItemValue
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_init() }
func file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_init() {
	if File_teams_reco_arch_colossusdb_proto_kess_config_dir_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigItemValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigDir); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyDirOp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyDirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_goTypes,
		DependencyIndexes: file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_depIdxs,
		EnumInfos:         file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_enumTypes,
		MessageInfos:      file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_msgTypes,
	}.Build()
	File_teams_reco_arch_colossusdb_proto_kess_config_dir_proto = out.File
	file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_rawDesc = nil
	file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_goTypes = nil
	file_teams_reco_arch_colossusdb_proto_kess_config_dir_proto_depIdxs = nil
}
