// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        (unknown)
// source: teams/reco-arch/colossusdb/proto/mock_onebox_admin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StopNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name"`
	NodeId      string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id"`
}

func (x *StopNodeRequest) Reset() {
	*x = StopNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopNodeRequest) ProtoMessage() {}

func (x *StopNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopNodeRequest.ProtoReflect.Descriptor instead.
func (*StopNodeRequest) Descriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDescGZIP(), []int{0}
}

func (x *StopNodeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StopNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type StartNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name"`
	NodeId      string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id"`
	Port        int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port"`
	Paz         string `protobuf:"bytes,4,opt,name=paz,proto3" json:"paz"`
	NodeIndex   string `protobuf:"bytes,5,opt,name=node_index,json=nodeIndex,proto3" json:"node_index"`
}

func (x *StartNodeRequest) Reset() {
	*x = StartNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNodeRequest) ProtoMessage() {}

func (x *StartNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNodeRequest.ProtoReflect.Descriptor instead.
func (*StartNodeRequest) Descriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDescGZIP(), []int{1}
}

func (x *StartNodeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StartNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StartNodeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StartNodeRequest) GetPaz() string {
	if x != nil {
		return x.Paz
	}
	return ""
}

func (x *StartNodeRequest) GetNodeIndex() string {
	if x != nil {
		return x.NodeIndex
	}
	return ""
}

var File_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto protoreflect.FileDescriptor

var file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDesc = []byte{
	0x0a, 0x38, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x2d, 0x61, 0x72, 0x63,
	0x68, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x6e, 0x65, 0x62, 0x6f, 0x78, 0x5f, 0x61,
	0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6c, 0x6f,
	0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x1a, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x72, 0x65,
	0x63, 0x6f, 0x2d, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73,
	0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x64,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x22, 0x93, 0x01, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x61, 0x7a,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x61, 0x7a, 0x12, 0x1d, 0x0a, 0x0a, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x32, 0xa7, 0x01, 0x0a, 0x0f, 0x4d,
	0x6f, 0x63, 0x6b, 0x4f, 0x6e, 0x65, 0x62, 0x6f, 0x78, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x48,
	0x0a, 0x08, 0x53, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6c,
	0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73,
	0x75, 0x73, 0x64, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73,
	0x64, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x61, 0x69, 0x73, 0x68, 0x6f, 0x75, 0x2f, 0x63, 0x6f, 0x6c, 0x6f,
	0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDescOnce sync.Once
	file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDescData = file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDesc
)

func file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDescGZIP() []byte {
	file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDescOnce.Do(func() {
		file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDescData)
	})
	return file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDescData
}

var file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_goTypes = []interface{}{
	(*StopNodeRequest)(nil),     // 0: colossusdb.StopNodeRequest
	(*StartNodeRequest)(nil),    // 1: colossusdb.StartNodeRequest
	(*ErrorStatusResponse)(nil), // 2: colossusdb.ErrorStatusResponse
}
var file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_depIdxs = []int32{
	0, // 0: colossusdb.MockOneboxAdmin.StopNode:input_type -> colossusdb.StopNodeRequest
	1, // 1: colossusdb.MockOneboxAdmin.StartNode:input_type -> colossusdb.StartNodeRequest
	2, // 2: colossusdb.MockOneboxAdmin.StopNode:output_type -> colossusdb.ErrorStatusResponse
	2, // 3: colossusdb.MockOneboxAdmin.StartNode:output_type -> colossusdb.ErrorStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_init() }
func file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_init() {
	if File_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto != nil {
		return
	}
	file_teams_reco_arch_colossusdb_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_goTypes,
		DependencyIndexes: file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_depIdxs,
		MessageInfos:      file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_msgTypes,
	}.Build()
	File_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto = out.File
	file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_rawDesc = nil
	file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_goTypes = nil
	file_teams_reco_arch_colossusdb_proto_mock_onebox_admin_proto_depIdxs = nil
}
