// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        (unknown)
// source: teams/reco-arch/colossusdb/proto/replica_location.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicaLocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// server_index refers to one entry in RouteEntries.servers
	ServerIndex int32             `protobuf:"varint,1,opt,name=server_index,json=serverIndex,proto3" json:"server_index"`
	Role        ReplicaRole       `protobuf:"varint,2,opt,name=role,proto3,enum=colossusdb.ReplicaRole" json:"role"`
	Info        map[string]string `protobuf:"bytes,3,rep,name=info,proto3" json:"-" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ReplicaLocation) Reset() {
	*x = ReplicaLocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_teams_reco_arch_colossusdb_proto_replica_location_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReplicaLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaLocation) ProtoMessage() {}

func (x *ReplicaLocation) ProtoReflect() protoreflect.Message {
	mi := &file_teams_reco_arch_colossusdb_proto_replica_location_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaLocation.ProtoReflect.Descriptor instead.
func (*ReplicaLocation) Descriptor() ([]byte, []int) {
	return file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicaLocation) GetServerIndex() int32 {
	if x != nil {
		return x.ServerIndex
	}
	return 0
}

func (x *ReplicaLocation) GetRole() ReplicaRole {
	if x != nil {
		return x.Role
	}
	return ReplicaRole_kPrimary
}

func (x *ReplicaLocation) GetInfo() map[string]string {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_teams_reco_arch_colossusdb_proto_replica_location_proto protoreflect.FileDescriptor

var file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDesc = []byte{
	0x0a, 0x37, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x2d, 0x61, 0x72, 0x63,
	0x68, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x72, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6c, 0x6f, 0x73,
	0x73, 0x75, 0x73, 0x64, 0x62, 0x1a, 0x2d, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2f, 0x72, 0x65, 0x63,
	0x6f, 0x2d, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64,
	0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2b, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x6f, 0x6c, 0x6f,
	0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x52, 0x6f,
	0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x39, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75,
	0x73, 0x64, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x1a, 0x37, 0x0a, 0x09, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x46, 0x0a, 0x1c,
	0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x75, 0x61, 0x69, 0x73, 0x68, 0x6f, 0x75, 0x2e, 0x72, 0x65, 0x63,
	0x6f, 0x2e, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x50, 0x01, 0x5a, 0x24,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x75, 0x61, 0x69, 0x73,
	0x68, 0x6f, 0x75, 0x2f, 0x63, 0x6f, 0x6c, 0x6f, 0x73, 0x73, 0x75, 0x73, 0x64, 0x62, 0x2f, 0x70,
	0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDescOnce sync.Once
	file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDescData = file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDesc
)

func file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDescGZIP() []byte {
	file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDescOnce.Do(func() {
		file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDescData = protoimpl.X.CompressGZIP(file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDescData)
	})
	return file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDescData
}

var file_teams_reco_arch_colossusdb_proto_replica_location_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_teams_reco_arch_colossusdb_proto_replica_location_proto_goTypes = []interface{}{
	(*ReplicaLocation)(nil), // 0: colossusdb.ReplicaLocation
	nil,                     // 1: colossusdb.ReplicaLocation.InfoEntry
	(ReplicaRole)(0),        // 2: colossusdb.ReplicaRole
}
var file_teams_reco_arch_colossusdb_proto_replica_location_proto_depIdxs = []int32{
	2, // 0: colossusdb.ReplicaLocation.role:type_name -> colossusdb.ReplicaRole
	1, // 1: colossusdb.ReplicaLocation.info:type_name -> colossusdb.ReplicaLocation.InfoEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_teams_reco_arch_colossusdb_proto_replica_location_proto_init() }
func file_teams_reco_arch_colossusdb_proto_replica_location_proto_init() {
	if File_teams_reco_arch_colossusdb_proto_replica_location_proto != nil {
		return
	}
	file_teams_reco_arch_colossusdb_proto_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_teams_reco_arch_colossusdb_proto_replica_location_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReplicaLocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_teams_reco_arch_colossusdb_proto_replica_location_proto_goTypes,
		DependencyIndexes: file_teams_reco_arch_colossusdb_proto_replica_location_proto_depIdxs,
		MessageInfos:      file_teams_reco_arch_colossusdb_proto_replica_location_proto_msgTypes,
	}.Build()
	File_teams_reco_arch_colossusdb_proto_replica_location_proto = out.File
	file_teams_reco_arch_colossusdb_proto_replica_location_proto_rawDesc = nil
	file_teams_reco_arch_colossusdb_proto_replica_location_proto_goTypes = nil
	file_teams_reco_arch_colossusdb_proto_replica_location_proto_depIdxs = nil
}
